### ISSUE TITLE
Implement Curve ZeroMQ Auth in Lisp

### ISSUE THREAD

**Issue by kalzoo** [rigetti/rpcq#111]
Per @ecpeterson in #100, adding this issue to track the addition of Curve ZeroMQ auth to the Lisp side of RPCq. 

In the near future, the only way to communicate with a Rigetti QPU will be using Curve auth. As long as all clients use the Python version of `rpcq` (or its consuming packages like `pyquil`) to communicate with the QPU, it's not necessary for the Lisp variant.

**Comment by ecpeterson** [comment]
Note: should we switch from zmq to https, this will be wasted effort.

**Comment by notmgsk** [comment]
> Note: should we switch from zmq to https, this will be wasted effort.

Is that a possibility / being discussed?

**Comment by ecpeterson** [comment]
Sure is. I don't know the timeline / the solidity of those plans, but it should enter into the calculus of whether doing this work (which includes finding / writing a ZMQ4 wrapper) is worth the time.
