### ISSUE TITLE
Does not build in SBCL 2.0.9 - conflict between slot :initform and :type

### ISSUE THREAD

**Issue by quicklisp** [rigetti/rpcq#138]
https://github.com/rigetti/rpcq/blob/33bfedccfdfc78338170defb91e7b46c0a4ea435/src/core-messages.lisp#L161

The `:type` of float and the `:initform` of NIL signal a full warning in SBCL 2.0.9. Build log here:

http://report.quicklisp.org/2020-09-29/failure-report/rpcq.html#rpcq

**Comment by notmgsk** [comment]
Thanks @quicklisp. Will fix.

**Comment by quicklisp** [comment]
Any word on this?
