### ISSUE TITLE
Syntax Error in Setup.py

### ISSUE THREAD

**Issue by obliviateandsurrender** [rigetti/rpcq#34]
While performing the installation using pip I receive a syntax error warning at the line 31: f.write(f'__version__ = \'{__version__}\'\n').
Using Python 3.5.2 and pip 9.0.1.

**Comment by ecp-rigetti** [comment]
For onlookers: f-strings are a feature new to python 3.6 (over 3.5). It would be great if we could loudly announce that this package requires python 3.6.
