### ISSUE TITLE
RPCErrorError: Execution timed out.  Note: time limit: 60 seconds.

### ISSUE THREAD

**Issue by vincentelfving** [rigetti/rpcq#39]
When asking a local `quilc -R` server to compile a particularly large quil program via `quil_to_native_quil`, I get the following error:
`rpcq._utils.RPCErrorError: Execution timed out.  Note: time limit: 60 seconds.`
A similar but shorter program compiles fine, and does not give the time-out.

I tried to find in the documentation how to set the time limit through the client-server framework, but all I found was that the default should have been infinite... I don't see where the 60 second limit comes from.

This may be a very trivial question, but how does a user set this time limit through the pyquil interface? What I tried so far:
```
from rpcq import Client
client = Client('tcp://localhost:5555')
client.timeout = 3600
```
Didn't affect the behaviour and raised the above error again.
`rpcq._utils.RPCErrorError: Execution timed out.  Note: time limit: 60 seconds.`

**Comment by ecp-rigetti** [comment]
The pyQuil interface can be used to set a client-side timeout, but it can't be used to set the server-side timeout: that's set for good on server launch. In the server code, I see an option to consume a time limit ( https://github.com/rigetti/quilc/blob/master/app/src/entry-point.lisp#L62 ) but then the action timeout is hard coded ( https://github.com/rigetti/quilc/blob/master/app/src/rpc-server.lisp#L172 )! I'll open an issue in quilc to address this.

It also looks like the semantics of a timeout value of `0` might differ in the two places: in the RPCQ server code https://github.com/rigetti/rpcq/blob/master/src/server.lisp#L202 , it looks like 0 might cause immediate termination of the RPC call, whereas quilc expects `0` to function as no timeout. It would be good to sanitize that too by changing the timeout predicate in the RPCQ code to `(and timeout (plusp timeout))` or so. (In the actual implementation of bordeaux-threads, it looks like `0` means no timeout is enforced, but this isn't stated in the docstrings.)

**Comment by notmgsk** [comment]
This is supported now by pyquil/quilc.
