### ISSUE TITLE
RPCErrorError should be renamed to RPCError

### ISSUE THREAD

**Issue by stevenheidel** [rigetti/rpcq#6]
The "RPCError" message needn't be exposed to the user so we can name the exception RPCError. Alternatively we could name it CommunicationError or something like this

**Comment by stevenheidel** [comment]
@mpharrigan - assigning this to you when you have time - by subclassing RPCErrorError this can be done pretty quickly in a backwards compatible way

**Comment by mpharrigan** [comment]
how do you want to hide `messages.RPCError`
