### ISSUE TITLE
Optionally provide the backtrace when catching host errors

### ISSUE THREAD

**Issue by notmgsk** [rigetti/rpcq#87]
`server.lisp` has a couple error handlers that catch all errors coming out of the host, and those handlers only provide the top-level error. It is helpful during debugging to inspect the backtrace but this is not available currently. One option would be to use `handler-bind` rather than `handler-case` (where the stack has already unwound), and provide something like `rpcq::*verbose-error*` to optionally provide more detailed errors.

**Comment by appleby** [comment]
I am currently looking into #75 and #61, which touch on related parts of the rcpq server code. If it's not urgent, I could possibly take a look at this as well while I'm mucking around in there.

**Comment by notmgsk** [comment]
> I am currently looking into #75 and #61, which touch on related parts of the rcpq server code. If it's not urgent, I could possibly take a look at this as well while I'm mucking around in there.

:big-chubby-rubbery-yellow-thumbs-up:
